<?php


/**
 * Implements hook_permission().
 */
function notificare_permission() {
  return array(
    'administer notificare' => array(
      'title' => t('Administer Notificare.'),
      'description' => t(''),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function notificare_menu() {
  $items['admin/config/workflow/notificare'] = array(
    'title' => 'Notificare admin settings',
    'description' => 'Configure Notificare',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('notificare_admin_settings'),
    'access arguments' => array('administer notificare'),
  );

  return $items;
}


/**
 * The admin form to save Service Token and User token.
 * Called from function notificare_menu().
 */
function notificare_admin_settings() {

  $form = array();

  $form['notificare'] = array(
    '#type' => 'fieldset',
    '#title' => t('Notificare Tokens'),
    '#description' => t('If you don\'t have a Notificare account yet,
      <a href="@signupURL">get one first</a>. Otherwise, go straight to your
      <a href="@createseriveURL">Dashboard</a> and create a Drupal service.',
      array(
        '@signupURL' => 'https://notifica.re/sign-up',
        '@createseriveURL' => 'https://notifica.re/dashboard/services',
        )
      ),
    );

  $form['notificare']['notificare_post_uri'] = array(
    '#type' => 'textfield',
    '#title' => t('Notificare Post URI'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('notificare_post_uri', 'https://apps.notifica.re'),
    );

  $form['notificare']['notificare_service'] = array(
    '#type' => 'textfield',
    '#title' => t('Notificare Service'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('notificare_service', 'hooks/wordpress'),
    );

  $form['notificare']['notificare_service_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Notificare Service Token'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('notificare_service_token', ''),
    );

  $form['notificare']['notificare_post_uri'] = array(
    '#type' => 'textfield',
    '#title' => t('Notificare Post URI'),
    '#size' => 60,
    '#required' => TRUE,
    '#default_value' => variable_get('notificare_post_uri', 'https://apps.notifica.re'),
    );

  $form['notificare']['notificare_user_token'] = array(
    '#type' => 'textfield',
    '#title' => t('Notificare User Token'),
    '#default_value' => variable_get('notificare_user_token', ''),
    '#required' => TRUE,
    );

  return system_settings_form($form);
}


/**
 * Implements hook_uninstall().
 */
function notificare_uninstall() {
  variable_del('notificare_post_uri');
  variable_del('notificare_service');
  variable_del('notificare_post_uri');
  variable_del('notificare_user_token');
}